version: "3.3"
services:
  web:
    image: php:8.2-apache
    hostname: php
    ports:
      - 8085:80
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mario
      - MYSQL_PASSWORD=mario12345
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=alumnos
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8800:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
